import { faker } from '@faker-js/faker'


const Cats = [
  {
    id: 1,
    name: faker.name.firstName(),
    breed: faker.animal.cat(),
    price: faker.commerce.price(80, 300, 0, ""),
    img: "https://cdn2.thecatapi.com/images/bh2.jpg",
    amount: 1,
  },
  {
    id: 2,
    name: faker.name.firstName(),
    breed: faker.animal.cat(),
    price: faker.commerce.price(80, 300, 0, ""),
    img: "https://cdn2.thecatapi.com/images/1cq.jpg",
    amount: 1,
  },
  {
    id: 3,
    name: faker.name.firstName(),
    breed: faker.animal.cat(),
    price: faker.commerce.price(80, 300, 0, ""),
    img: "https://cdn2.thecatapi.com/images/5HsSLvDP8.jpg",
    amount: 1,
  },
  {
    id: 4,
    name: faker.name.firstName(),
    breed: faker.animal.cat(),
    price: faker.commerce.price(80, 300, 0, ""),
    img: "https://cdn2.thecatapi.com/images/e7q.jpg",
    amount: 1,
  },
  {
    id: 5,
    name: faker.name.firstName(),
    breed: faker.animal.cat(),
    price: faker.commerce.price(80, 300, 0, ""),
    img: "https://cdn2.thecatapi.com/images/z3CV7NACl.jpg",
    amount: 1,
  },
  {
    id: 6,
    name: faker.name.firstName(),
    breed: faker.animal.cat(),
    price: faker.commerce.price(80, 300, 0, ""),
    img: "https://cdn2.thecatapi.com/images/G2Bjld1gJ.jpg",
    amount: 1,
  },
  {
    id: 7,
    name: faker.name.firstName(),
    breed: faker.animal.cat(),
    price: faker.commerce.price(80, 300, 0, ""),
    img: "https://cdn2.thecatapi.com/images/ifSXadgxQ.jpg",
    amount: 1,
  },
  {
    id: 8,
    name: faker.name.firstName(),
    breed: faker.animal.cat(),
    price: faker.commerce.price(80, 300, 0, ""),
    img: "https://cdn2.thecatapi.com/images/c8j.jpg",
    amount: 1,
  },
  {
    id: 9,
    name: faker.name.firstName(),
    breed: faker.animal.cat(),
    price: faker.commerce.price(80, 300, 0, ""),
    img: "https://cdn2.thecatapi.com/images/MTgzMDcyMA.jpg",
       amount: 1,
  },
  {
    id: 10,
    name: faker.name.firstName(),
    breed: faker.animal.cat(),
    price: faker.commerce.price(80, 300, 0, ""),
    img: "https://cdn2.thecatapi.com/images/3fh.jpg",
    amount: 1,
  },
  {
    id: 11,
    name: faker.name.firstName(),
    breed: faker.animal.cat(),
    price: faker.commerce.price(80, 300, 0, ""),
    img: "https://cdn2.thecatapi.com/images/2jh.jpg",
    amount: 1,
  },
  {
    id: 12,
    name: faker.name.firstName(),
    breed: faker.animal.cat(),
    price: faker.commerce.price(80, 300, 0, ""),
    img: "https://cdn2.thecatapi.com/images/9dh.jpg",
    amount: 1,
  },
];

export default Cats;
