const list = [
    {
      id: 1,
      title: "",
      author: "",
      price: 89,
      img: "https://cdn2.thecatapi.com/images/f5.jpg",
      amount: 1,
    },
    {
      id: 2,
      title: "",
      author: "",
      price: 98,
      img: "https://cdn2.thecatapi.com/images/fZS8WqaYm.jpg",
      amount: 1,
    },
    {
      id: 3,
      title: "",
      author: "",
      price: 143,
      img: "https://cdn2.thecatapi.com/images/anf.jpg",
      amount: 1,
    },
    {
      id: 4,
      title: "",
      author: "",
      price: 57,
      img: "https://cdn2.thecatapi.com/images/MjA3OTE1MA.jpg",
      amount: 1,
    },
    {
      id: 5,
      title: "",
      author: "",
      price: 149,
      img: "https://cdn2.thecatapi.com/images/5nr.jpg",
      amount: 1,
    },
    {
      id: 6,
      title: "",
      author: "",
      price: 135,
      img: "https://cdn2.thecatapi.com/images/al5.jpg",
      amount: 1,
    },
    {
      id: 7,
      title: "",
      author: "by Om Books Editorial Team  | 1 January 2021",
      price: 693,
      img: "https://cdn2.thecatapi.com/images/and.jpg",
      amount: 1,
    },
    {
      id: 8,
      title: "",
      author: "by Wonder House Books  | 6 December 2020",
      price: 289,
      img: "https://cdn2.thecatapi.com/images/a6g.jpg",
      amount: 1,
    },
    {
      id: 9,
      title: "",
      author: "by Content Team at Target Publications",
      price: 80,
      img: "https://cdn2.thecatapi.com/images/RHs33lRPC.jpg",
      amount: 1,
    },
    {
      id: 10,
      title: "",
      author: "by Maple Press | 1 September 2021",
      price: 86,
      img: "https://cdn2.thecatapi.com/images/vKcrwdUwo.jpg",
      amount: 1,
    },
    {
      id: 11,
      title: "",
      author: "by Rebecca Smith  | 14 December 2021",
      price: 120,
      img: "https://cdn2.thecatapi.com/images/kw9n_n4-X.jpg",
      amount: 1,
    },
    {
      id: 12,
      title: "",
      author: "by Sudha Murty | 1 January 2015",
      price: 157,
      img: "https://cdn2.thecatapi.com/images/xbP4iLqKT.jpg",
      amount: 1,
    },
  ];
  
  export default list;